openapi: 3.0.0
x-stoplight:
  id: eb1ce132dafe1
info:
  title: Diagnostics
  version: '1.0'
  description: API Diagnostics для создания планов-графиков испытаний электрооборудования
  contact: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/bachurrina/Diagnostics/1.0
  - url: 'http://diagnostics.ru'
paths:
  /substations:
    parameters: []
    get:
      summary: Получить список подстанций
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    substationID:
                      type: integer
                    substationName:
                      type: string
                    substationVoltage:
                      type: string
                    area:
                      type: string
                    startDt:
                      type: string
                x-examples:
                  example-1:
                    - substationID: 1
                      substationName: Поляны
                      substationVoltage: 110 кВ
                      area: Рязанский уч.
                      startDt: '2004-01-01'
              examples:
                example-1:
                  value:
                    - substationID: 1
                      substationName: Поляны
                      substationVoltage: 110 кВ
                      area: Рязанский уч.
                      startDt: '2004-01-01'
        '500':
          description: Internal Server Error
      operationId: get-substations
      description: Отображает список всех подстанций
      tags:
        - Structure
      parameters:
        - schema:
            type: string
          in: query
          name: voltage
          description: Напряжение
        - schema:
            type: string
          in: query
          name: area
          description: Участок
  '/substations/{substationID}':
    parameters:
      - schema:
          type: integer
        name: substationID
        in: path
        required: true
        description: ID Подстанции
    get:
      summary: Получить информацию о подстанции
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    substation:
                      substationID: 0
                      substationName: string
                      substationVoltage: string
                      area: string
                      startDt: string
                    equipment:
                      - equipmentID: 0
                        equipmentName: string
                        substationID: 0
                        substationName: string
                        equipmentVoltagee: string
                        classID: 0
                        class: string
                        type: string
                        startDt: string
                        tetsDt: string
                        status: string
                properties:
                  substation:
                    type: object
                    properties:
                      substationID:
                        type: integer
                      substationName:
                        type: string
                      substationVoltage:
                        type: string
                      area:
                        type: string
                      startDt:
                        type: string
                  equipment:
                    type: array
                    items:
                      type: object
                      properties:
                        equipmentID:
                          type: integer
                        equipmentName:
                          type: string
                        substationID:
                          type: integer
                        substationName:
                          type: string
                        equipmentVoltage:
                          type: string
                        classID:
                          type: integer
                        class:
                          type: string
                        type:
                          type: string
                        startDt:
                          type: string
                        tetsDt:
                          type: string
                        status:
                          type: string
              examples:
                example-1:
                  value:
                    substation:
                      substationID: 1
                      substationName: Поляны
                      substationVoltage: 110 кВ
                      area: Рязанский уч.
                      startDt: '2004-01-01'
                    equipment:
                      - equipmentID: 1
                        equipmentName: Т-1
                        substationID: 1
                        substationName: Поляны
                        equipmentVoltage: 110 кВ
                        classID: 1
                        class: Трансформатор
                        type: Масляный
                        startDt: '2004-01-01'
                        tetsDt: '2004-01-01'
                        status: Эксплуатация
          headers: {}
        '404':
          description: Not Found
          headers: {}
        '500':
          description: Internal Server Error
      operationId: get-substations-substationID
      description: Возвращает информацию о ПС и список ЕО
      tags:
        - Structure
      parameters:
        - schema:
            type: string
          in: query
          name: Напряжение ЕО
          description: equipmentVoltage
        - schema:
            type: string
          in: query
          name: Класс ЕО
          description: class
        - schema:
            type: string
          in: query
          name: Тип ЕО
          description: type
  '/substations/{substationID}/equipment':
    post:
      summary: Создать новую единицу оборудования
      operationId: post-substations-substationID-equipments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                equipmentName:
                  type: string
                substationID:
                  type: integer
                substationName:
                  type: string
                equipmentVoltagee:
                  type: string
                classID:
                  type: integer
                class:
                  type: string
                type:
                  type: string
                startDt:
                  type: string
                  format: date
                tetsDt:
                  type: string
                  format: date
                status:
                  type: string
                  default: Эксплуатация
              required:
                - equipmentName
                - substationName
                - equipmentVoltagee
                - class
                - type
                - startDt
                - tetsDt
                - status
            examples:
              example-1:
                value:
                  equipmentName: ТТ-1
                  substationID: 1
                  substationName: Поляны
                  equipmentVoltagee: 110 кВ
                  classID: 6
                  class: Трансформатор тока
                  type: Масляный
                  startDt: '2022-05-05'
                  tetsDt: '2022-04-28'
                  status: Эксплуатация
        description: Информация о новой ЕО
      description: Создает новую единицу оборудования со статусом "Эксплуатация"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  equipmentID:
                    type: integer
                  equipmentName:
                    type: string
                  substationID:
                    type: integer
                  substationName:
                    type: string
                  equipmentVoltagee:
                    type: string
                  classID:
                    type: integer
                  class:
                    type: string
                  type:
                    type: string
                  startDt:
                    type: string
                  tetsDt:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    equipmentID: 50
                    equipmentName: Т-3
                    substationID: 2
                    substationName: Рязань
                    equipmentVoltagee: 110 кВ
                    classID: 1
                    class: Трансформатор
                    type: Масляный
                    startDt: '2022-03-03'
                    tetsDt: '2022-03-02'
                    status: Эксплуатация
              examples:
                example-1:
                  value:
                    equipmentID: 50
                    equipmentName: ТТ-1
                    substationID: 1
                    substationName: Поляны
                    equipmentVoltagee: 110 кВ
                    classID: 6
                    class: Трансформатор тока
                    type: Маляный
                    startDt: '2022-05-05'
                    tetsDt: '2020-04-28'
                    status: Эксплуатация
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      tags:
        - Structure
      parameters: []
    parameters:
      - schema:
          type: integer
        name: substationID
        in: path
        required: true
        description: ID ПС
  '/substations/{substationID}/equipments/{equipmentID}':
    parameters:
      - schema:
          type: integer
        name: substationID
        in: path
        required: true
        description: ID Подстанции
      - schema:
          type: integer
        name: equipmentID
        in: path
        required: true
        description: ID ЕО
    patch:
      summary: Информация о единице оборудования
      operationId: get-substations-substationID-equipments-equipmentID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  endDt:
                    type: string
                  status:
                    type: string
                required:
                  - status
              examples:
                example-1:
                  value:
                    endDt: '2022-04-05'
                    status: Выведена
        '400':
          description: Invalid endDt
        '500':
          description: Internal Server Error
      description: Присваевает ЕО статус "Выведена"
      parameters: []
      tags:
        - Structure
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  endDT: string
                  status: string
              properties:
                equipmentID:
                  type: integer
                endDt:
                  type: string
                status:
                  type: string
            examples:
              example-1:
                value:
                  equipmentID: 3
                  endDt: '2022-04-05'
                  status: Выведена
        description: Дата вывода из эксплуатации
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: Structure
